---
settings:
  name: BlueXP volume caching
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti per il caching del volume BlueXP
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - section: support
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
