---
sidebar: sidebar 
permalink: get-started/cache-prerequisites.html 
keywords: what are bluexp volume caching requirements, volume caching prerequisites 
summary: 'Inizia a utilizzare il caching dei volumi BlueXP verificando il supporto per il tuo ambiente, l"accesso alla rete, l"accesso e il browser Web.' 
---
= Prerequisiti per il caching del volume BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Inizia verificando la preparazione del tuo ambiente operativo, dell'accesso, dell'accesso alla rete e del browser Web.

Per utilizzare il caching dei volumi BlueXP, è necessario assicurarsi che l'ambiente soddisfi tutti i requisiti.

* ONTAP 9.8 e versioni successive
+
** Autorizzazioni Cluster Admin ONTAP
** Intercluster di LIF sui cluster


* In BlueXP:
+
** Il connettore BlueXP deve essere configurato in NetApp BlueXP. Tutti i cluster di origine e destinazione devono trovarsi sullo stesso connettore BlueXP. Fare riferimento a. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["Avvio rapido di BlueXP"^] e. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Scopri di più sui connettori"^].
** L'ambiente di lavoro deve essere impostato.
** I cluster devono essere aggiunti nell'ambiente di lavoro di destinazione e IN uno stato ATTIVO o degradato.
** Requisiti BlueXP standard. Fare riferimento a. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisiti BlueXP"].



