---
sidebar: sidebar 
permalink: release-notes/cache-limitations.html 
keywords: volume caching, bluexp 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa release del servizio o che non interagiscono correttamente con esso. 
---
= Limitazioni note
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa release del servizio o che non interagiscono correttamente con esso.



== Limitazione nella copia delle regole dei criteri di esportazione della cache

Le regole dei criteri di esportazione della cache non vengono copiate nel volume della cache nelle seguenti situazioni:

* Quando l'ambiente di lavoro del volume di origine è Amazon FSX per NetApp ONTAP o Cloud Volumes ONTAP e il volume cache è ONTAP 9.10.1 o versione precedente.
* Quando l'ambiente di lavoro del volume di origine è una qualsiasi versione di ONTAP e il volume cache è ONTAP 9.10.1 o versione precedente.


Soluzione alternativa: Creare manualmente le regole per il volume della cache.



== La creazione della cache non riesce per le VM storage con lo stesso nome

Se i cluster di origine e di destinazione utilizzano VM di storage con lo stesso nome, la cache non viene creata.

Soluzione alternativa: Utilizzare nomi diversi per le VM di storage di origine e di destinazione.



== Ritardo nella visualizzazione di policy di esportazione nuove o modificate di recente

Quando si crea una cache, potrebbe non essere possibile visualizzare un criterio di esportazione creato o modificato di recente nell'elenco.

Soluzione: Riprovare in pochi minuti.



== La creazione della cache non riesce quando la destinazione ha attivato solo il protocollo CIFS

La creazione della cache non riesce se il cluster di origine o di destinazione ha ONTAP 9.10.1 o versione precedente e il cluster di destinazione ha attivato solo il protocollo CIFS.

Soluzione alternativa: Utilizzare un cluster di destinazione con ONTAP 9.11.1 o versione successiva o con entrambi i protocolli CIFS e NFS configurati.
